/*
 * Books API
 * The Books API provides information about book reviews and The New York Times Best Sellers lists.  ## Best Sellers Lists Services ### List Names The lists/names service returns a list of all the NYT Best Sellers Lists.  Some lists are published weekly and others monthly.  The response includes when each list was first published and last published.  ``` /lists/names.json ```  ### List Data  The lists/{date}/{name} service returns the books on the best sellers list for the specified date and list name.  ``` /lists/2019-01-20/hardcover-fiction.json ```  Use \"current\" for {date} to get the latest list. ``` /lists/current/hardcover-fiction.json ```  ## Book Reviews Services  The book reviews service lets you get NYT book review by author, ISBN, or title.  ``` /reviews.json?author=Michelle+Obama ```  ``` /reviews.json?isbn=9781524763138 ```  ``` /reviews.json?title=Becoming ```  ## Example Calls  ``` https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/books/v3/reviews.json?author=Stephen+King&api-key=yourkey ``` 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ListGetBestSellersResponseResultsInnerBookDetailsInner
 */
public class ListGetBestSellersResponseResultsInnerBookDetailsInnerTest {
    private final ListGetBestSellersResponseResultsInnerBookDetailsInner model = new ListGetBestSellersResponseResultsInnerBookDetailsInner();

    /**
     * Model tests for ListGetBestSellersResponseResultsInnerBookDetailsInner
     */
    @Test
    public void testListGetBestSellersResponseResultsInnerBookDetailsInner() {
        // TODO: test ListGetBestSellersResponseResultsInnerBookDetailsInner
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'contributor'
     */
    @Test
    public void contributorTest() {
        // TODO: test contributor
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'contributorNote'
     */
    @Test
    public void contributorNoteTest() {
        // TODO: test contributorNote
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'ageGroup'
     */
    @Test
    public void ageGroupTest() {
        // TODO: test ageGroup
    }

    /**
     * Test the property 'publisher'
     */
    @Test
    public void publisherTest() {
        // TODO: test publisher
    }

    /**
     * Test the property 'primaryIsbn13'
     */
    @Test
    public void primaryIsbn13Test() {
        // TODO: test primaryIsbn13
    }

    /**
     * Test the property 'primaryIsbn10'
     */
    @Test
    public void primaryIsbn10Test() {
        // TODO: test primaryIsbn10
    }

}
