/*
 * Books API
 * The Books API provides information about book reviews and The New York Times Best Sellers lists.  ## Best Sellers Lists Services ### List Names The lists/names service returns a list of all the NYT Best Sellers Lists.  Some lists are published weekly and others monthly.  The response includes when each list was first published and last published.  ``` /lists/names.json ```  ### List Data  The lists/{date}/{name} service returns the books on the best sellers list for the specified date and list name.  ``` /lists/2019-01-20/hardcover-fiction.json ```  Use \"current\" for {date} to get the latest list. ``` /lists/current/hardcover-fiction.json ```  ## Book Reviews Services  The book reviews service lets you get NYT book review by author, ISBN, or title.  ``` /reviews.json?author=Michelle+Obama ```  ``` /reviews.json?isbn=9781524763138 ```  ``` /reviews.json?title=Becoming ```  ## Example Calls  ``` https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/books/v3/reviews.json?author=Stephen+King&api-key=yourkey ``` 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ListGetHistoryResponseResultsInnerRanksHistoryInner
 */
public class ListGetHistoryResponseResultsInnerRanksHistoryInnerTest {
    private final ListGetHistoryResponseResultsInnerRanksHistoryInner model = new ListGetHistoryResponseResultsInnerRanksHistoryInner();

    /**
     * Model tests for ListGetHistoryResponseResultsInnerRanksHistoryInner
     */
    @Test
    public void testListGetHistoryResponseResultsInnerRanksHistoryInner() {
        // TODO: test ListGetHistoryResponseResultsInnerRanksHistoryInner
    }

    /**
     * Test the property 'primaryIsbn10'
     */
    @Test
    public void primaryIsbn10Test() {
        // TODO: test primaryIsbn10
    }

    /**
     * Test the property 'primaryIsbn13'
     */
    @Test
    public void primaryIsbn13Test() {
        // TODO: test primaryIsbn13
    }

    /**
     * Test the property 'rank'
     */
    @Test
    public void rankTest() {
        // TODO: test rank
    }

    /**
     * Test the property 'listName'
     */
    @Test
    public void listNameTest() {
        // TODO: test listName
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'publishedDate'
     */
    @Test
    public void publishedDateTest() {
        // TODO: test publishedDate
    }

    /**
     * Test the property 'bestsellersDate'
     */
    @Test
    public void bestsellersDateTest() {
        // TODO: test bestsellersDate
    }

    /**
     * Test the property 'weeksOnList'
     */
    @Test
    public void weeksOnListTest() {
        // TODO: test weeksOnList
    }

    /**
     * Test the property 'ranksLastWeek'
     */
    @Test
    public void ranksLastWeekTest() {
        // TODO: test ranksLastWeek
    }

    /**
     * Test the property 'asterisk'
     */
    @Test
    public void asteriskTest() {
        // TODO: test asterisk
    }

    /**
     * Test the property 'dagger'
     */
    @Test
    public void daggerTest() {
        // TODO: test dagger
    }

}
