/*
 * Books API
 * The Books API provides information about book reviews and The New York Times Best Sellers lists.  ## Best Sellers Lists Services ### List Names The lists/names service returns a list of all the NYT Best Sellers Lists.  Some lists are published weekly and others monthly.  The response includes when each list was first published and last published.  ``` /lists/names.json ```  ### List Data  The lists/{date}/{name} service returns the books on the best sellers list for the specified date and list name.  ``` /lists/2019-01-20/hardcover-fiction.json ```  Use \"current\" for {date} to get the latest list. ``` /lists/current/hardcover-fiction.json ```  ## Book Reviews Services  The book reviews service lets you get NYT book review by author, ISBN, or title.  ``` /reviews.json?author=Michelle+Obama ```  ``` /reviews.json?isbn=9781524763138 ```  ``` /reviews.json?title=Becoming ```  ## Example Calls  ``` https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/books/v3/reviews.json?author=Stephen+King&api-key=yourkey ``` 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReviewGetBookReviewsResponseResultsInner
 */
public class ReviewGetBookReviewsResponseResultsInnerTest {
    private final ReviewGetBookReviewsResponseResultsInner model = new ReviewGetBookReviewsResponseResultsInner();

    /**
     * Model tests for ReviewGetBookReviewsResponseResultsInner
     */
    @Test
    public void testReviewGetBookReviewsResponseResultsInner() {
        // TODO: test ReviewGetBookReviewsResponseResultsInner
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'publicationDt'
     */
    @Test
    public void publicationDtTest() {
        // TODO: test publicationDt
    }

    /**
     * Test the property 'byline'
     */
    @Test
    public void bylineTest() {
        // TODO: test byline
    }

    /**
     * Test the property 'bookTitle'
     */
    @Test
    public void bookTitleTest() {
        // TODO: test bookTitle
    }

    /**
     * Test the property 'bookAuthor'
     */
    @Test
    public void bookAuthorTest() {
        // TODO: test bookAuthor
    }

    /**
     * Test the property 'isbn13'
     */
    @Test
    public void isbn13Test() {
        // TODO: test isbn13
    }

}
