/*
 * Books API
 * The Books API provides information about book reviews and The New York Times Best Sellers lists.  ## Best Sellers Lists Services ### List Names The lists/names service returns a list of all the NYT Best Sellers Lists.  Some lists are published weekly and others monthly.  The response includes when each list was first published and last published.  ``` /lists/names.json ```  ### List Data  The lists/{date}/{name} service returns the books on the best sellers list for the specified date and list name.  ``` /lists/2019-01-20/hardcover-fiction.json ```  Use \"current\" for {date} to get the latest list. ``` /lists/current/hardcover-fiction.json ```  ## Book Reviews Services  The book reviews service lets you get NYT book review by author, ISBN, or title.  ``` /reviews.json?author=Michelle+Obama ```  ``` /reviews.json?isbn=9781524763138 ```  ``` /reviews.json?title=Becoming ```  ## Example Calls  ``` https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=yourkey ```  ``` https://api.nytimes.com/svc/books/v3/reviews.json?author=Stephen+King&api-key=yourkey ``` 
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ListGetBestSellersResponseResultsInnerIsbnsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ListGetBestSellersResponseResultsInnerIsbnsInner {
  public static final String SERIALIZED_NAME_ISBN10 = "isbn10";
  @SerializedName(SERIALIZED_NAME_ISBN10)
  private String isbn10;

  public static final String SERIALIZED_NAME_ISBN13 = "isbn13";
  @SerializedName(SERIALIZED_NAME_ISBN13)
  private String isbn13;

  public ListGetBestSellersResponseResultsInnerIsbnsInner() {
  }

  public ListGetBestSellersResponseResultsInnerIsbnsInner isbn10(String isbn10) {
    
    
    
    
    this.isbn10 = isbn10;
    return this;
  }

   /**
   * Get isbn10
   * @return isbn10
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIsbn10() {
    return isbn10;
  }


  public void setIsbn10(String isbn10) {
    
    
    
    this.isbn10 = isbn10;
  }


  public ListGetBestSellersResponseResultsInnerIsbnsInner isbn13(String isbn13) {
    
    
    
    
    this.isbn13 = isbn13;
    return this;
  }

   /**
   * Get isbn13
   * @return isbn13
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIsbn13() {
    return isbn13;
  }


  public void setIsbn13(String isbn13) {
    
    
    
    this.isbn13 = isbn13;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ListGetBestSellersResponseResultsInnerIsbnsInner instance itself
   */
  public ListGetBestSellersResponseResultsInnerIsbnsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListGetBestSellersResponseResultsInnerIsbnsInner listGetBestSellersResponseResultsInnerIsbnsInner = (ListGetBestSellersResponseResultsInnerIsbnsInner) o;
    return Objects.equals(this.isbn10, listGetBestSellersResponseResultsInnerIsbnsInner.isbn10) &&
        Objects.equals(this.isbn13, listGetBestSellersResponseResultsInnerIsbnsInner.isbn13)&&
        Objects.equals(this.additionalProperties, listGetBestSellersResponseResultsInnerIsbnsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isbn10, isbn13, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListGetBestSellersResponseResultsInnerIsbnsInner {\n");
    sb.append("    isbn10: ").append(toIndentedString(isbn10)).append("\n");
    sb.append("    isbn13: ").append(toIndentedString(isbn13)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isbn10");
    openapiFields.add("isbn13");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ListGetBestSellersResponseResultsInnerIsbnsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ListGetBestSellersResponseResultsInnerIsbnsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListGetBestSellersResponseResultsInnerIsbnsInner is not found in the empty JSON string", ListGetBestSellersResponseResultsInnerIsbnsInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("isbn10") != null && !jsonObj.get("isbn10").isJsonNull()) && !jsonObj.get("isbn10").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isbn10` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isbn10").toString()));
      }
      if ((jsonObj.get("isbn13") != null && !jsonObj.get("isbn13").isJsonNull()) && !jsonObj.get("isbn13").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isbn13` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isbn13").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListGetBestSellersResponseResultsInnerIsbnsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListGetBestSellersResponseResultsInnerIsbnsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListGetBestSellersResponseResultsInnerIsbnsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListGetBestSellersResponseResultsInnerIsbnsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ListGetBestSellersResponseResultsInnerIsbnsInner>() {
           @Override
           public void write(JsonWriter out, ListGetBestSellersResponseResultsInnerIsbnsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ListGetBestSellersResponseResultsInnerIsbnsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ListGetBestSellersResponseResultsInnerIsbnsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ListGetBestSellersResponseResultsInnerIsbnsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ListGetBestSellersResponseResultsInnerIsbnsInner
  * @throws IOException if the JSON string is invalid with respect to ListGetBestSellersResponseResultsInnerIsbnsInner
  */
  public static ListGetBestSellersResponseResultsInnerIsbnsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListGetBestSellersResponseResultsInnerIsbnsInner.class);
  }

 /**
  * Convert an instance of ListGetBestSellersResponseResultsInnerIsbnsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

